baseURL: "https://shuvojitmsft.github.io/"
languageCode: en-us
title: Shuvojit's folio
theme: PaperMod

params:
 
    homeInfoParams:
        Title: This is the personal blog of Mr. Shuvojit Ray Chaudhuri
        Content: Service Engineer at Microsoft.
